name: Markdown Lint

on:
  push:
    paths:
      - 'README.md'

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: avto-dev/markdown-lint@v1
        with:
          config: '.github/linters/linters.yml'